# Generated by Django 5.2.9 on 2025-12-16 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_user_date_joined"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OTP",
        ),
    ]
