# Generated by Django 5.2.9 on 2025-12-22 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_delete_otp"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
