# Generated by Django 5.2.9 on 2026-05-11 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_user_created_at_user_groups_user_is_superuser_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="عنوان آدرس (مثلاً خانه، محل کار)",
                    ),
                ),
                ("province", models.CharField(max_length=100, verbose_name="استان")),
                ("city", models.CharField(max_length=100, verbose_name="شهر")),
                (
                    "district",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="منطقه/محله"
                    ),
                ),
                ("address_detail", models.TextField(verbose_name="آدرس کامل")),
                (
                    "postal_code",
                    models.CharField(blank=True, max_length=20, verbose_name="کد پستی"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=11, verbose_name="تلفن تماس"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, verbose_name="آدرس پیش\u200cفرض"
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="عرض جغرافیایی",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="طول جغرافیایی",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "آدرس",
                "verbose_name_plural": "آدرس\u200cها",
                "ordering": ["-is_default", "-created_at"],
            },
        ),
    ]
