# Generated by Django 5.2.9 on 2026-06-06 04:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationForAdvertising",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
                ("message", models.TextField()),
                ("brand", models.CharField(max_length=100)),
                ("link", models.CharField(max_length=100)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("month_key", models.CharField(editable=False, max_length=7)),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "ارسال موفق"), ("failed", "ارسال ناموفق")],
                        default="success",
                        max_length=10,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product_pricing",
                    models.ManyToManyField(
                        blank=True,
                        related_name="pricing_notifications",
                        to="products.productpricingtab",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("created_by", "month_key"),
                        name="uniq_ad_notification_per_month_per_user",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="NotificationForLate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("message", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "ارسال موفق"), ("failed", "ارسال ناموفق")],
                        default="success",
                        max_length=10,
                    ),
                ),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="late_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["status", "create_time"],
                        name="notificatio_status_87f478_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SmsLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=20, verbose_name="شماره گیرنده"),
                ),
                ("message", models.TextField(verbose_name="متن پیامک")),
                (
                    "sms_type",
                    models.CharField(
                        choices=[
                            ("order_paid", "پرداخت سفارش"),
                            ("order_delivered", "تحویل سفارش"),
                            ("order_canceled", "کنسلی سفارش"),
                            ("seller_cancel_report", "گزارش کنسلی به فروشنده"),
                            ("daily_report", "گزارش روزانه فروشنده"),
                            ("coupon", "کوپن تخفیف"),
                            ("global_discount", "تخفیف سراسری"),
                            ("advertising", "تبلیغاتی"),
                            ("late_notification", "یادآوری تأخیر"),
                            ("other", "سایر"),
                        ],
                        default="other",
                        max_length=30,
                        verbose_name="نوع پیامک",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار"),
                            ("sent", "ارسال شد"),
                            ("failed", "ناموفق"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان ارسال"
                    ),
                ),
                (
                    "provider_response",
                    models.TextField(
                        blank=True, null=True, verbose_name="پاسخ سرویس پیامک"
                    ),
                ),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "گزارش پیامک",
                "verbose_name_plural": "گزارش\u200cهای پیامک",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["phone_number", "sms_type"],
                        name="notificatio_phone_n_8538bc_idx",
                    ),
                    models.Index(
                        fields=["status"], name="notificatio_status_532cc1_idx"
                    ),
                ],
            },
        ),
    ]
