version: '3.8'

services:
  drf:
    build : .
    command : python manage.py runserver 0.0.0.0:8000
    volumes:
      - . :/app
    ports:
      - "8000:8000"
    depends_on:
      - redis


  redis:
    image: redis:7.1.0


  celery:
    build: .
    command: celery -A bokhar worker --loglevel=info
    depends_on:
      - redis
