# Generated by Django 5.2.9 on 2025-12-26 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="size",
            name="length",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="size",
            name="single_double",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="size",
            name="width",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
