# Generated by Django 5.2.9 on 2026-02-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
