# Generated by Django 5.2.9 on 2025-12-31 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_alter_size_length_alter_size_single_double_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="is_active_code",
        ),
        migrations.RemoveField(
            model_name="product",
            name="new_price",
        ),
    ]
