# Generated by Django 5.2.9 on 2026-05-31 16:00

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("order", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gateway_account_id",
                    models.CharField(
                        help_text="شناسه حساب در زرین\u200cپال (id)",
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("iban", models.CharField(max_length=34, unique=True)),
                ("holder_name", models.CharField(blank=True, max_length=255)),
                (
                    "bank_name",
                    models.CharField(
                        blank=True, help_text="نام بانک صادرکننده", max_length=255
                    ),
                ),
                (
                    "bank_slug",
                    models.CharField(
                        blank=True, help_text="اسلاگ بانک مثلاً pasargad", max_length=100
                    ),
                ),
                (
                    "is_legal",
                    models.BooleanField(default=False, help_text="حساب حقوقی؟"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("personal", "مغازه\u200cدار"), ("share", "تیم")],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار"),
                            ("active", "فعال"),
                            ("rejected", "رد شده"),
                            ("expired", "منقضی"),
                            ("deleted", "حذف شده"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("raw_response", models.JSONField(default=dict)),
                ("expired_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "حساب بانکی",
                "verbose_name_plural": "حساب\u200cهای بانکی",
            },
        ),
        migrations.CreateModel(
            name="IdempotencyKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("endpoint", models.CharField(max_length=255)),
                ("request_hash", models.CharField(max_length=255)),
                ("response_status", models.IntegerField(blank=True, null=True)),
                ("is_processed", models.BooleanField(default=False)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("response_data", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        default=backend.wallet.models.models.default_expires_at
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="idempotency_keys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "type_pay",
                    models.CharField(
                        choices=[("wallet", "Wallet"), ("gatway", "Gatway")]
                    ),
                ),
                ("amount", models.BigIntegerField()),
                ("fee_amount", models.BigIntegerField(default=0)),
                (
                    "authority",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "ref_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("curency", models.CharField(default="IRT", max_length=255)),
                ("card_pan", models.CharField(blank=True, max_length=30)),
                ("card_hash", models.CharField(max_length=255)),
                ("payer_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("gateway_request", models.JSONField(default=dict)),
                ("gateway_response", models.JSONField(default=dict)),
                ("verify_response", models.JSONField(default=dict)),
                ("callback_payload", models.JSONField(default=dict)),
                ("response_code", models.IntegerField(blank=True, null=True)),
                ("fail_reason", models.TextField(blank=True)),
                ("expire_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initiated", "ایجاد شده"),
                            ("pending", "در انتظار"),
                            ("paid", "پرداخت شده"),
                            ("failed", "ناموفق"),
                            ("canceled", "لغو شده"),
                            ("expired", "منقضی شده"),
                            ("refunded", "ریفاند شده"),
                        ],
                        default="initiated",
                        max_length=30,
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("refunded_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="order.order",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaymentAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("authority", models.CharField(db_index=True, max_length=255)),
                ("ref_id", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initiated", "Initiated"),
                            ("callback_received", "Callback Received"),
                            ("verified", "Verified"),
                            ("failed", "Failed"),
                        ],
                        max_length=30,
                    ),
                ),
                ("gateway_response", models.JSONField(default=dict)),
                ("callback_payload", models.JSONField(default=dict)),
                ("payer_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("idempotency_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="wallet.paymentsession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaymentTerminal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "terminal_id",
                    models.CharField(
                        db_index=True,
                        help_text="شناسه درگاه در زرین\u200cپال (همان id)",
                        max_length=225,
                        unique=True,
                    ),
                ),
                (
                    "merchant_id",
                    models.CharField(
                        help_text="مرچنت کد (key)", max_length=255, unique=True
                    ),
                ),
                (
                    "mcc",
                    models.CharField(
                        blank=True,
                        help_text="کد دسته\u200cبندی صنف",
                        max_length=10,
                        null=True,
                    ),
                ),
                ("support_phone", models.CharField(max_length=15)),
                ("name", models.CharField(max_length=255)),
                ("logo", models.URLField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار پرداخت"),
                            ("active", "فعال"),
                            ("suspended", "معلق"),
                            ("rejected", "رد شده"),
                            ("deleted", "حذف شده"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "mode",
                    models.BooleanField(
                        default=False, help_text="False برای تست، True برای تولید"
                    ),
                ),
                (
                    "daily_limit",
                    models.PositiveBigIntegerField(
                        default=0, help_text="محدودیت روزانه به ریال"
                    ),
                ),
                (
                    "monthly_limit",
                    models.PositiveBigIntegerField(
                        default=0, help_text="محدودیت ماهانه به ریال"
                    ),
                ),
                (
                    "webhook_url",
                    models.URLField(
                        blank=True,
                        help_text="آدرس وب\u200cهوک برای اطلاع\u200cرسانی تراکنش\u200cها",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "raw_response",
                    models.JSONField(
                        default=dict, help_text="پاسخ کامل API هنگام ثبت درگاه"
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_terminals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "preferred_bank_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="preferred_for_terminals",
                        to="wallet.bankaccount",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="paymentsession",
            name="terminal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="wallet.paymentterminal",
            ),
        ),
        migrations.CreateModel(
            name="PaymentWebhookLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payload", models.JSONField()),
                ("headers", models.JSONField(default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("signature_valid", models.BooleanField(default=False)),
                ("processed", models.BooleanField(default=False)),
                ("response_data", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "terminal",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="wallet.paymentterminal",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RefundRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "amount",
                    models.BigIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("canceled", "Canceled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("idempotency_key", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refund_requests",
                        to="order.order",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refund_requests",
                        to="wallet.paymentsession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refund_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Settlement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.BigIntegerField()),
                ("reference_id", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                            ("reversed", "Reversed"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                ("payable_at", models.DateTimeField()),
                ("reconciled_at", models.DateTimeField(blank=True, null=True)),
                ("raw_response", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bank_account",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="wallet.bankaccount",
                    ),
                ),
                (
                    "terminal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wallet.paymentterminal",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TerminalAllowedDomain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domain", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "terminal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allowed_domains",
                        to="wallet.paymentterminal",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TerminalBankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("settlement_priority", models.PositiveIntegerField(default=1)),
                (
                    "settlement_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=100,
                        help_text="درصد تسویه به این حساب",
                        max_digits=5,
                    ),
                ),
                (
                    "settlement_type",
                    models.CharField(
                        choices=[("primary", "اصلی"), ("partner", "شریک")],
                        default="primary",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bank_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="terminal_links",
                        to="wallet.bankaccount",
                    ),
                ),
                (
                    "terminal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="terminal_bank_accounts",
                        to="wallet.paymentterminal",
                    ),
                ),
            ],
            options={
                "verbose_name": "حساب بانکی درگاه",
                "verbose_name_plural": "حساب\u200cهای بانکی درگاه",
                "ordering": ["settlement_priority"],
            },
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("available_balance", models.BigIntegerField(default=0)),
                ("locked_balance", models.BigIntegerField(default=0)),
                ("withdraw_blocked_util", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "amount",
                    models.BigIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("deposit", "Deposit"),
                            ("payment", "Payment"),
                            ("refundwallet", "Refundtowallet"),
                            ("withdrawal", "Withdrawal"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("trace_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("available_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="order.order",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wallet_transactions",
                        to="wallet.paymentsession",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="wallet.wallet",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WithdrawalRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "method",
                    models.CharField(choices=[("card", "Card"), ("paya", "Paya")]),
                ),
                (
                    "amount",
                    models.BigIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("bank_name", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("failure_reason", models.TextField(blank=True)),
                ("idempotency_key", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "deposit_payment",
                    models.ForeignKey(
                        help_text="تراکنش شارژی که باید به آن استرداد شود",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="withdrawal_requests",
                        to="wallet.paymentsession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="withdrawal_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="withdrawals",
                        to="wallet.wallet",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="bankaccount",
            index=models.Index(fields=["iban"], name="wallet_bank_iban_fcda12_idx"),
        ),
        migrations.AddIndex(
            model_name="bankaccount",
            index=models.Index(fields=["status"], name="wallet_bank_status_d154e8_idx"),
        ),
        migrations.AddIndex(
            model_name="idempotencykey",
            index=models.Index(fields=["key"], name="wallet_idem_key_e078a3_idx"),
        ),
        migrations.AddIndex(
            model_name="idempotencykey",
            index=models.Index(
                fields=["created_at"], name="wallet_idem_created_c0ec49_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="idempotencykey",
            index=models.Index(
                fields=["is_processed"], name="wallet_idem_is_proc_0d878f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentattempt",
            index=models.Index(
                fields=["authority"], name="wallet_paym_authori_8f122e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentattempt",
            index=models.Index(fields=["status"], name="wallet_paym_status_e9010a_idx"),
        ),
        migrations.AddIndex(
            model_name="paymentterminal",
            index=models.Index(
                fields=["created_at"], name="wallet_paym_created_a240cc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentterminal",
            index=models.Index(
                fields=["terminal_id"], name="wallet_paym_termina_77474c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentterminal",
            index=models.Index(fields=["status"], name="wallet_paym_status_6090d1_idx"),
        ),
        migrations.AddIndex(
            model_name="paymentsession",
            index=models.Index(fields=["status"], name="wallet_paym_status_95df0e_idx"),
        ),
        migrations.AddIndex(
            model_name="paymentsession",
            index=models.Index(
                fields=["authority"], name="wallet_paym_authori_92fc93_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentsession",
            index=models.Index(fields=["ref_id"], name="wallet_paym_ref_id_7e4119_idx"),
        ),
        migrations.AddIndex(
            model_name="paymentsession",
            index=models.Index(
                fields=["created_at"], name="wallet_paym_created_0c4f1a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentwebhooklog",
            index=models.Index(
                fields=["processed"], name="wallet_paym_process_b07211_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentwebhooklog",
            index=models.Index(
                fields=["created_at"], name="wallet_paym_created_33bfe5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="refundrequest",
            index=models.Index(fields=["status"], name="wallet_refu_status_ceb07c_idx"),
        ),
        migrations.AddIndex(
            model_name="refundrequest",
            index=models.Index(
                fields=["created_at"], name="wallet_refu_created_8219ad_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="refundrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="refund_amount_gt_zero"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="terminalbankaccount",
            unique_together={("terminal", "bank_account")},
        ),
        migrations.AddIndex(
            model_name="wallet",
            index=models.Index(
                fields=["is_active"], name="wallet_wall_is_acti_632cdc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["transaction_type"], name="wallet_tran_transac_7debff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["status"], name="wallet_tran_status_a49b73_idx"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["created_at"], name="wallet_tran_created_fb97c1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="withdrawalrequest",
            index=models.Index(fields=["status"], name="wallet_with_status_f692e5_idx"),
        ),
        migrations.AddIndex(
            model_name="withdrawalrequest",
            index=models.Index(
                fields=["created_at"], name="wallet_with_created_0aa711_idx"
            ),
        ),
    ]
