# Generated by Django 5.2.9 on 2026-04-16 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discounts", "0001_initial"),
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productdiscount",
            options={
                "verbose_name": "Product/Category/PricingTab Discount",
                "verbose_name_plural": "Product Discounts",
            },
        ),
        migrations.AddField(
            model_name="coupon",
            name="min_order_price",
            field=models.PositiveIntegerField(
                blank=True, help_text="حداقل مبلغ سفارش برای اعمال کوپن", null=True
            ),
        ),
        migrations.AddField(
            model_name="coupon",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coupons",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="productdiscount",
            name="end_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productdiscount",
            name="start_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="type",
            field=models.CharField(
                choices=[("percent", "درصدی"), ("fixed", "مبلغ ثابت")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="usage_limit",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="used_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="value",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="globaldiscount",
            name="end_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="globaldiscount",
            name="start_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="globaldiscount",
            name="type",
            field=models.CharField(
                choices=[("percent", "درصدی"), ("fixed", "مبلغ ثابت")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="globaldiscount",
            name="value",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="productdiscount",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="discounts",
                to="products.category",
            ),
        ),
        migrations.AlterField(
            model_name="productdiscount",
            name="material",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="discounts",
                to="products.materialprice",
            ),
        ),
        migrations.AlterField(
            model_name="productdiscount",
            name="pricing_tab",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="discounts",
                to="products.productpricingtab",
            ),
        ),
        migrations.AlterField(
            model_name="productdiscount",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="discounts",
                to="products.product",
            ),
        ),
        migrations.AlterField(
            model_name="productdiscount",
            name="type",
            field=models.CharField(
                choices=[("percent", "درصدی"), ("fixed", "مبلغ ثابت")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="productdiscount",
            name="value",
            field=models.PositiveIntegerField(),
        ),
        migrations.AddIndex(
            model_name="coupon",
            index=models.Index(
                fields=["is_active"], name="discounts_c_is_acti_e0e563_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="coupon",
            index=models.Index(
                fields=["start_at"], name="discounts_c_start_a_0ee39c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="coupon",
            index=models.Index(fields=["end_at"], name="discounts_c_end_at_fe6d0a_idx"),
        ),
        migrations.AddIndex(
            model_name="coupon",
            index=models.Index(fields=["code"], name="discounts_c_code_3b6115_idx"),
        ),
        migrations.AddIndex(
            model_name="globaldiscount",
            index=models.Index(
                fields=["is_active"], name="discounts_g_is_acti_63fb53_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="globaldiscount",
            index=models.Index(
                fields=["start_at"], name="discounts_g_start_a_b197b3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="globaldiscount",
            index=models.Index(fields=["end_at"], name="discounts_g_end_at_6a0aa0_idx"),
        ),
        migrations.AddIndex(
            model_name="productdiscount",
            index=models.Index(
                fields=["is_active"], name="discounts_p_is_acti_b4cbc0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productdiscount",
            index=models.Index(
                fields=["start_at"], name="discounts_p_start_a_c8fc08_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productdiscount",
            index=models.Index(fields=["end_at"], name="discounts_p_end_at_641149_idx"),
        ),
    ]
