# Generated by Django 5.2.9 on 2026-04-16 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "discounts",
            "0002_alter_productdiscount_options_coupon_min_order_price_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productdiscount",
            options={},
        ),
        migrations.AlterField(
            model_name="coupon",
            name="min_order_price",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
