# Generated by Django 5.2.9 on 2026-05-10 10:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discounts", "0003_alter_productdiscount_options_and_more"),
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coupon",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveIndex(
            model_name="coupon",
            name="discounts_c_start_a_0ee39c_idx",
        ),
        migrations.RemoveIndex(
            model_name="coupon",
            name="discounts_c_end_at_fe6d0a_idx",
        ),
        migrations.RemoveIndex(
            model_name="productdiscount",
            name="discounts_p_is_acti_b4cbc0_idx",
        ),
        migrations.RemoveIndex(
            model_name="productdiscount",
            name="discounts_p_start_a_c8fc08_idx",
        ),
        migrations.RemoveIndex(
            model_name="productdiscount",
            name="discounts_p_end_at_641149_idx",
        ),
        migrations.RemoveField(
            model_name="coupon",
            name="end_at",
        ),
        migrations.RemoveField(
            model_name="coupon",
            name="min_order_price",
        ),
        migrations.RemoveField(
            model_name="coupon",
            name="start_at",
        ),
        migrations.AddField(
            model_name="coupon",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="coupon",
            name="ends_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاریخ پایان"
            ),
        ),
        migrations.AddField(
            model_name="coupon",
            name="min_order_amount",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="حداقل مبلغ سفارش"
            ),
        ),
        migrations.AddField(
            model_name="coupon",
            name="starts_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاریخ شروع"
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="code",
            field=models.CharField(
                blank=True, max_length=50, unique=True, verbose_name="کد تخفیف"
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="فعال"),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="type",
            field=models.CharField(
                choices=[("percent", "درصدی"), ("fixed", "مبلغ ثابت")],
                max_length=10,
                verbose_name="نوع تخفیف",
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="usage_limit",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="حداکثر تعداد استفاده"
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="used_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="تعداد استفاده شده"
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coupons",
                to=settings.AUTH_USER_MODEL,
                verbose_name="کاربر خاص (اختیاری)",
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="value",
            field=models.PositiveIntegerField(verbose_name="مقدار"),
        ),
        migrations.AlterField(
            model_name="productdiscount",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_discounts",
                to="products.category",
            ),
        ),
        migrations.AddIndex(
            model_name="coupon",
            index=models.Index(
                fields=["starts_at"], name="discounts_c_starts__3a768b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="coupon",
            index=models.Index(
                fields=["ends_at"], name="discounts_c_ends_at_d86418_idx"
            ),
        ),
    ]
