# Generated by Django 5.2.9 on 2026-06-06 04:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalDiscount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("percent", "درصدی"), ("fixed", "مبلغ ثابت")],
                        max_length=10,
                    ),
                ),
                ("value", models.PositiveIntegerField()),
                ("start_at", models.DateTimeField(blank=True, null=True)),
                ("end_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["is_active"], name="discounts_g_is_acti_63fb53_idx"
                    ),
                    models.Index(
                        fields=["start_at"], name="discounts_g_start_a_b197b3_idx"
                    ),
                    models.Index(
                        fields=["end_at"], name="discounts_g_end_at_6a0aa0_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProductDiscount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("percent", "درصدی"), ("fixed", "مبلغ ثابت")],
                        max_length=10,
                    ),
                ),
                ("value", models.PositiveIntegerField()),
                ("start_at", models.DateTimeField(blank=True, null=True)),
                ("end_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_discounts",
                        to="products.category",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discounts",
                        to="products.materialprice",
                    ),
                ),
                (
                    "pricing_tab",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discounts",
                        to="products.productpricingtab",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discounts",
                        to="products.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=50, unique=True, verbose_name="کد تخفیف"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("percent", "درصدی"), ("fixed", "مبلغ ثابت")],
                        max_length=10,
                        verbose_name="نوع تخفیف",
                    ),
                ),
                ("value", models.PositiveIntegerField(verbose_name="مقدار")),
                (
                    "usage_limit",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="حداکثر تعداد استفاده"
                    ),
                ),
                (
                    "used_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="تعداد استفاده شده"
                    ),
                ),
                (
                    "min_order_amount",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="حداقل مبلغ سفارش"
                    ),
                ),
                (
                    "starts_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاریخ شروع"
                    ),
                ),
                (
                    "ends_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاریخ پایان"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coupons",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر خاص (اختیاری)",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["code"], name="discounts_c_code_3b6115_idx"),
                    models.Index(
                        fields=["is_active"], name="discounts_c_is_acti_e0e563_idx"
                    ),
                    models.Index(
                        fields=["starts_at"], name="discounts_c_starts__3a768b_idx"
                    ),
                    models.Index(
                        fields=["ends_at"], name="discounts_c_ends_at_d86418_idx"
                    ),
                ],
            },
        ),
    ]
