# Generated by Django 5.2.9 on 2026-05-07 09:49

import django.db.models.deletion
import order.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("discount", "0001_initial"),
        ("product", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time_shift",
                    models.CharField(
                        choices=[("morning", "صبح (۸–۱۳)"), ("evening", "عصر (۱۶–۲۰)")],
                        default="morning",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("capacity", models.PositiveIntegerField(default=20)),
                ("urgent_24_capacity", models.PositiveIntegerField(default=5)),
                ("urgent_48_capacity", models.PositiveIntegerField(default=10)),
                ("base_price", models.PositiveIntegerField(default=0)),
                ("price_add", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "شیفت تحویل\u200cدهی",
            },
        ),
        migrations.CreateModel(
            name="PickUpTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time_shift",
                    models.CharField(
                        choices=[("morning", "صبح (۸–۱۳)"), ("evening", "عصر (۱۶–۲۰)")],
                        default="morning",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("capacity", models.PositiveIntegerField(default=20)),
                ("base_price", models.PositiveIntegerField(default=0)),
                ("price_add", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "شیفت تحویل\u200cگیری",
            },
        ),
        migrations.CreateModel(
            name="RushFeeSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tomorrow_fee", models.PositiveIntegerField(default=50000)),
                ("day_after_tomorrow_fee", models.PositiveIntegerField(default=25000)),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("percent_tomorrow_fee", models.PositiveIntegerField(default=0)),
                (
                    "percent_day_after_tomorrow_fee",
                    models.PositiveIntegerField(default=0),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pickup_date", models.DateField()),
                (
                    "pickup_shift",
                    models.CharField(
                        choices=[("morning", "صبح (۸–۱۳)"), ("evening", "عصر (۱۶–۲۰)")],
                        default="morning",
                        max_length=20,
                    ),
                ),
                ("delivery_date", models.DateField()),
                (
                    "delivery_shift",
                    models.CharField(
                        choices=[("morning", "صبح (۸–۱۳)"), ("evening", "عصر (۱۶–۲۰)")],
                        default="morning",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار پرداخت "),
                            ("paid", "پرداخت شده"),
                            ("picked_up", "دریافت از مشتری"),
                            ("washing", "در حال شستشو"),
                            ("delivered", "تحویل داده شده"),
                            ("canceled", "لغو شده بعد 15 دقیقه "),
                            ("returned", "برگشتی "),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("pickup_cost", models.PositiveIntegerField(default=0)),
                ("delivery_cost", models.PositiveIntegerField(default=0)),
                ("percent_fee", models.PositiveIntegerField(default=0)),
                ("rush_fee", models.PositiveIntegerField(default=0)),
                ("subtotal_raw", models.PositiveIntegerField(default=0)),
                ("total_item_discounts", models.PositiveIntegerField(default=0)),
                ("subtotal_after_items", models.PositiveIntegerField(default=0)),
                ("order_discount_amount", models.PositiveIntegerField(default=0)),
                ("final_price", models.PositiveIntegerField(default=0)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("order_type", models.CharField(max_length=20)),
                (
                    "address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="users.address",
                    ),
                ),
                (
                    "applied_coupon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="discount.coupon",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=models.SET(order.models.get_deleted_users),
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("material", models.CharField(max_length=50)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("original_price", models.PositiveIntegerField()),
                ("item_discount", models.PositiveIntegerField(default=0)),
                ("price", models.PositiveIntegerField()),
                (
                    "applied_product_discount",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_items",
                        to="discount.productdiscount",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_items",
                        to="order.order",
                    ),
                ),
                (
                    "pricing_tab",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_items",
                        to="product.productpricingtab",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_items",
                        to="product.product",
                    ),
                ),
                (
                    "size",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_items",
                        to="product.size",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderStatusLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("from_status", models.CharField(blank=True, max_length=20, null=True)),
                ("to_status", models.CharField(max_length=20)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="order.order"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["status", "user"], name="order_order_status_e3f191_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["pickup_date", "pickup_shift"],
                name="order_order_pickup__b3055e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["delivery_date", "delivery_shift"],
                name="order_order_deliver_fe798f_idx",
            ),
        ),
    ]
