# Generated by Django 5.2.9 on 2026-05-15 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discounts", "0004_alter_coupon_options_and_more"),
        ("order", "0001_initial"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rushfeesetting",
            options={
                "verbose_name": "تنظیمات هزینه فوری",
                "verbose_name_plural": "تنظیمات هزینه فوری",
            },
        ),
        migrations.RemoveField(
            model_name="deliverytemplate",
            name="capacity",
        ),
        migrations.RemoveField(
            model_name="pickuptemplate",
            name="capacity",
        ),
        migrations.RemoveField(
            model_name="rushfeesetting",
            name="day_after_tomorrow_fee",
        ),
        migrations.RemoveField(
            model_name="rushfeesetting",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="rushfeesetting",
            name="percent_day_after_tomorrow_fee",
        ),
        migrations.RemoveField(
            model_name="rushfeesetting",
            name="percent_tomorrow_fee",
        ),
        migrations.RemoveField(
            model_name="rushfeesetting",
            name="tomorrow_fee",
        ),
        migrations.AddField(
            model_name="rushfeesetting",
            name="fee_24h",
            field=models.PositiveIntegerField(
                default=50000, verbose_name="هزینه ۲۴ ساعته"
            ),
        ),
        migrations.AddField(
            model_name="rushfeesetting",
            name="fee_48h",
            field=models.PositiveIntegerField(
                default=25000, verbose_name="هزینه ۴۸ ساعته"
            ),
        ),
        migrations.AddField(
            model_name="rushfeesetting",
            name="is_24h_enabled",
            field=models.BooleanField(default=True, verbose_name="فعال بودن ۲۴ ساعته"),
        ),
        migrations.AddField(
            model_name="rushfeesetting",
            name="is_48h_enabled",
            field=models.BooleanField(default=True, verbose_name="فعال بودن ۴۸ ساعته"),
        ),
        migrations.AddField(
            model_name="rushfeesetting",
            name="percent_24h",
            field=models.PositiveIntegerField(default=0, verbose_name="درصد ۲۴ ساعته"),
        ),
        migrations.AddField(
            model_name="rushfeesetting",
            name="percent_48h",
            field=models.PositiveIntegerField(default=0, verbose_name="درصد ۴۸ ساعته"),
        ),
        migrations.AlterField(
            model_name="order",
            name="applied_coupon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="discounts.coupon",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_type",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("paid", "پرداخت شده"),
                    ("picked_up", "دریافت از مشتری"),
                    ("washing", "در حال شستشو"),
                    ("delivered", "تحویل داده شده"),
                    ("canceled", "لغو شده  "),
                    ("returned", "برگشتی "),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="applied_product_discount",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_items",
                to="discounts.productdiscount",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="pricing_tab",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_items",
                to="products.productpricingtab",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_items",
                to="products.product",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="size",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_items",
                to="products.size",
            ),
        ),
    ]
