# Generated by Django 5.2.9 on 2026-05-16 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_alter_rushfeesetting_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverytemplate",
            name="disabled_dates",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="لیست تاریخ\u200cهای میلادی مثل ['2024-03-15', '2024-03-20']",
                verbose_name="تاریخ\u200cهای غیرفعال",
            ),
        ),
    ]
