# Generated by Django 5.2.9 on 2026-05-16 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0003_deliverytemplate_disabled_dates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliverytemplate",
            name="disabled_dates",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="لیست تاریخ\u200cهای غیرفعال (YYYY-MM-DD)",
            ),
        ),
    ]
